/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BackupRouteImport } from './routes/backup'
import { Route as CablesRouteImport } from './routes/cables'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as LabelsRouteImport } from './routes/labels'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as SystemsRouteImport } from './routes/systems'
import { Route as WhatIfRouteImport } from './routes/what-if'
import { Route as RoomsRoomIdRouteImport } from './routes/rooms.$roomId'
import { Route as SystemsSystemIdRouteImport } from './routes/systems.$systemId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupRoute = BackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const CablesRoute = CablesRouteImport.update({
  id: '/cables',
  path: '/cables',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const LabelsRoute = LabelsRouteImport.update({
  id: '/labels',
  path: '/labels',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemsRoute = SystemsRouteImport.update({
  id: '/systems',
  path: '/systems',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatIfRoute = WhatIfRouteImport.update({
  id: '/what-if',
  path: '/what-if',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoomIdRoute = RoomsRoomIdRouteImport.update({
  id: '/$roomId',
  path: '/$roomId',
  getParentRoute: () => RoomsRoute,
} as any)
const SystemsSystemIdRoute = SystemsSystemIdRouteImport.update({
  id: '/$systemId',
  path: '/$systemId',
  getParentRoute: () => SystemsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backup': typeof BackupRoute
  '/cables': typeof CablesRoute
  '/guide': typeof GuideRoute
  '/insights': typeof InsightsRoute
  '/inventory': typeof InventoryRoute
  '/labels': typeof LabelsRoute
  '/rooms': typeof RoomsRouteWithChildren
  '/systems': typeof SystemsRouteWithChildren
  '/what-if': typeof WhatIfRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/systems/$systemId': typeof SystemsSystemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backup': typeof BackupRoute
  '/cables': typeof CablesRoute
  '/guide': typeof GuideRoute
  '/insights': typeof InsightsRoute
  '/inventory': typeof InventoryRoute
  '/labels': typeof LabelsRoute
  '/rooms': typeof RoomsRouteWithChildren
  '/systems': typeof SystemsRouteWithChildren
  '/what-if': typeof WhatIfRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/systems/$systemId': typeof SystemsSystemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backup': typeof BackupRoute
  '/cables': typeof CablesRoute
  '/guide': typeof GuideRoute
  '/insights': typeof InsightsRoute
  '/inventory': typeof InventoryRoute
  '/labels': typeof LabelsRoute
  '/rooms': typeof RoomsRouteWithChildren
  '/systems': typeof SystemsRouteWithChildren
  '/what-if': typeof WhatIfRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/systems/$systemId': typeof SystemsSystemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backup'
    | '/cables'
    | '/guide'
    | '/insights'
    | '/inventory'
    | '/labels'
    | '/rooms'
    | '/systems'
    | '/what-if'
    | '/rooms/$roomId'
    | '/systems/$systemId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backup'
    | '/cables'
    | '/guide'
    | '/insights'
    | '/inventory'
    | '/labels'
    | '/rooms'
    | '/systems'
    | '/what-if'
    | '/rooms/$roomId'
    | '/systems/$systemId'
  id:
    | '__root__'
    | '/'
    | '/backup'
    | '/cables'
    | '/guide'
    | '/insights'
    | '/inventory'
    | '/labels'
    | '/rooms'
    | '/systems'
    | '/what-if'
    | '/rooms/$roomId'
    | '/systems/$systemId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BackupRoute: typeof BackupRoute
  CablesRoute: typeof CablesRoute
  GuideRoute: typeof GuideRoute
  InsightsRoute: typeof InsightsRoute
  InventoryRoute: typeof InventoryRoute
  LabelsRoute: typeof LabelsRoute
  RoomsRoute: typeof RoomsRouteWithChildren
  SystemsRoute: typeof SystemsRouteWithChildren
  WhatIfRoute: typeof WhatIfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backup': {
      id: '/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof BackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cables': {
      id: '/cables'
      path: '/cables'
      fullPath: '/cables'
      preLoaderRoute: typeof CablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labels': {
      id: '/labels'
      path: '/labels'
      fullPath: '/labels'
      preLoaderRoute: typeof LabelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/systems': {
      id: '/systems'
      path: '/systems'
      fullPath: '/systems'
      preLoaderRoute: typeof SystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-if': {
      id: '/what-if'
      path: '/what-if'
      fullPath: '/what-if'
      preLoaderRoute: typeof WhatIfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$roomId': {
      id: '/rooms/$roomId'
      path: '/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof RoomsRoomIdRouteImport
      parentRoute: typeof RoomsRoute
    }
    '/systems/$systemId': {
      id: '/systems/$systemId'
      path: '/$systemId'
      fullPath: '/systems/$systemId'
      preLoaderRoute: typeof SystemsSystemIdRouteImport
      parentRoute: typeof SystemsRoute
    }
  }
}

interface RoomsRouteChildren {
  RoomsRoomIdRoute: typeof RoomsRoomIdRoute
}

const RoomsRouteChildren: RoomsRouteChildren = {
  RoomsRoomIdRoute: RoomsRoomIdRoute,
}

const RoomsRouteWithChildren = RoomsRoute._addFileChildren(RoomsRouteChildren)

interface SystemsRouteChildren {
  SystemsSystemIdRoute: typeof SystemsSystemIdRoute
}

const SystemsRouteChildren: SystemsRouteChildren = {
  SystemsSystemIdRoute: SystemsSystemIdRoute,
}

const SystemsRouteWithChildren =
  SystemsRoute._addFileChildren(SystemsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BackupRoute: BackupRoute,
  CablesRoute: CablesRoute,
  GuideRoute: GuideRoute,
  InsightsRoute: InsightsRoute,
  InventoryRoute: InventoryRoute,
  LabelsRoute: LabelsRoute,
  RoomsRoute: RoomsRouteWithChildren,
  SystemsRoute: SystemsRouteWithChildren,
  WhatIfRoute: WhatIfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
